"""Settings"""

# Screen Settings
SCREEN_WIDTH = 60
SCREEN_HEIGHT = 60

# Reward for landing on food
FOOD_REWARD = 50

# For how many steps the snake will be rewarded (resets after hitting food)
STEP_REWARD = 1
KILL_AFTER_STEPS = 200
MAXIMUM_STEP_REWARD = 30

LEARNING_RATE = 0.002 

NUM_EVAL_EPISODES = 25
REPLAY_BUFFER_MAX_LENGTH = 100000
INITIAL_COLLECTION_STEPS = 100

BATCH_SIZE = 64
NUM_ITERATIONS = 500000

LOG_INTERVAL = 500
EVAL_INTERVAL = 2000
COLLECT_STEPS_PER_ITERATION = 10